# Coda environment to facilitate Biotite development process.
name: springcraft-dev

channels:
  - conda-forge

dependencies:
  - python=3.12
  - hatch
  # project dependencies
  - biotite>=1.6
  - numpy>=2.0
  - scipy>=1.12
  # docs dependencies
  - pymol-open-source>=3.1
