# Coda environment to facilitate Biotite development process.
# After creating the environment install the required packages with
#   poetry config virtualenvs.create false
#   poetry install
name: springcraft-dev

channels:
  - conda-forge

dependencies:
  - poetry
  - python=3.11
